## Back Propogation using PyTorch

In [1]:
import torch

In [2]:
# Computing the derivatives for Back Propogation

x = torch.tensor(4.0, requires_grad=True)

In [3]:
x

tensor(4., requires_grad=True)

In [4]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [5]:
# Back Propogation equation will be y = 2*x

y.backward()

In [6]:
print(x.grad)

tensor(8.)


In [7]:
lst = [[2.0, 3.0, 1.0], [4.0, 5.0, 3.0], [7.0, 6.0, 4.0]]

torch_input = torch.tensor(lst, requires_grad=True)

In [8]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [9]:
# y = x**3 + x**2
# y' = 3*(x**2) + 2*x

y = torch_input**3 + torch_input**2

In [10]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [11]:
z = y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [12]:
z.backward()

In [13]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])