In [1]:
import torch

In [2]:
torch.__version__

'1.5.1+cu101'

In [3]:
import numpy as np

In [4]:
lst = [3, 4, 5, 6]
arr = np.array(lst)

In [5]:
arr.dtype

dtype('int64')

## Converting Numpy to PyTorch Tensors

In [6]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [7]:
tensors[:2]

tensor([3, 4])

In [8]:
tensors.dtype

torch.int64

In [9]:
tensors[1:4]

tensor([4, 5, 6])

In [10]:
## Disadvantage of from_numpy. The array and tensor use the same memory location
tensors[3] = 100

In [11]:
tensors

tensor([  3,   4,   5, 100])

In [12]:
arr

array([  3,   4,   5, 100])

In [13]:
# Prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [14]:
tensor_arr[3] = 20
print(tensor_arr)
print(arr)

tensor([ 3,  4,  5, 20])
[  3   4   5 100]


In [15]:
# Zeroes and Ones
torch.zeros(2, 3, dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [16]:
torch.ones(2, 3, dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [17]:
a = torch.tensor(np.arange(0, 15).reshape(5,3))

In [18]:
a[:, 0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]])

### Arithmetic Operation

In [19]:
a = torch.tensor([3, 4, 5], dtype=torch.float)
b = torch.tensor([4, 5, 6], dtype=torch.float)

print(a + b)

tensor([ 7.,  9., 11.])


In [20]:
torch.add(a, b)

tensor([ 7.,  9., 11.])

In [21]:
c = torch.zeros(3)

In [22]:
torch.add(a, b, out=c)

tensor([ 7.,  9., 11.])

In [23]:
c

tensor([ 7.,  9., 11.])

In [24]:
# Some more operations

a = torch.tensor([3, 4, 5], dtype=torch.float)
b = torch.tensor([4, 5, 6], dtype=torch.float)

torch.add(a, b).sum()

tensor(27.)

### Dot Products and Multiplication Operations

In [25]:
x = torch.tensor([3, 4, 5], dtype=torch.float)
y = torch.tensor([4, 5, 6], dtype=torch.float)

In [26]:
# 3*4, 4*5, 6*5

x.mul(y)

tensor([12., 20., 30.])

In [27]:
# 3*4 + 4*5 + 6*5

x.dot(y)

tensor(62.)

### Matrix Multiplication

In [28]:
x = torch.tensor([[1, 4, 2], [1, 5, 5]], dtype=torch.float)
y = torch.tensor([[5, 7], [8, 6], [9, 11]], dtype=torch.float)

In [29]:
torch.matmul(x, y)

tensor([[55., 53.],
        [90., 92.]])

In [30]:
torch.mm(x, y)

tensor([[55., 53.],
        [90., 92.]])

In [31]:
x@y

tensor([[55., 53.],
        [90., 92.]])